language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  global:
  - secure: "SDTHNohoPqakqSNphTHvscpa+58IR15XVLpeg9/C8eQE9wFCEe6yjNq7vC0De5aFsDIxa5EHdjWJK0VIHXl4vUg6R8HaAl1bdRxYfHPCN4FxLW2Og88ekGsmHuGzh9h/P/3y7xidoh5PBP8O8srqs0uzYfOi+2Je/CjcHsE/zWhnWz5NUGUZscSPSjO0lo2lOaf2s1W7VegWVVR2gABx1Lb+Kzrbi+rvJl/qkuO8wXQykXxXGN2EimUfRvcUciLKrFtwwXXPNe4ReiW3mYxLPl0RyKBxsWz30+mYUM6SuZWVigU8ESQzRmB0ae5ubL4qMjk2fDHt8azWm2XtAHWU+ts6IVpM4XuvlEv9aX9c9dq9hZkLHlxlCQx8jhnmgXeaXM58iZINhUfhtwhbC20TTVURDZVffGi9wEhqhnZtRumVSXvQF9yrSqBO6MfGsQ/0/Ll+edg5pabnr/wlz1SIe904GOd6yPvMMJMEnyEz4K/s+9AkPwM7WimLyBqtCIizTy033F6UD01cIIfXwZ5b/ueRM0l8Vk6iNEsyE2eZGjn9e9xjWWAQVn9U9HpPKWIDiJCGkEQy6N33ue9uiRWhrEAUDf7WEiG0VBEpl4k+18i/mYak/RDo2y7EERwgsfZeiJyiY6N0vwOViDClCooxltw/qiqWp1jswUMtIzz7KDs="
  - secure: "COWFkQA4jlJq/NKvzAdsDw/CMZXp6X+Jmd76M/a0MZu174IFNeM7W3/rPhLEfHYL4NQPJdaf3uZL/t4LZv0C9t43+vTQlIORShKDQFPgJ3wp6mYx7oELLr27Dey+9hgbWg1Wp2AAaHSyT35va8XAqmUnNHpaZQmBvZbr7hFtGgbqdV4ieQPvHx7vvU9fciymDpTgrBEZg6B7G/voy4+7mgdPQKDfysQWxEAZqfKidzHC38a3Sm5Q//D8KO9+tQ6dcNCue/LHdGTDArE1nnnC4lw88VYlHxZ6XkM5SRMTtjocQm8qhYlneDzoLuGUHYrRdjz61BCDE90SEf2dSMjt3uCNDoG6uuQoIrlQ+UpOHPqwGeWgFfcmlFKFZA5AC6YdMtaLXHViln/ayuj/secmVghe1z+C6JWE5Pm25bCyVkyvbAUPrTRy7mHcTfgr2YRfZu4j+8Y7UZGMGdsl+o8vSH/WO3mlezhKWbnQvN6Nn70sYAxeq3K50V8fo+1zy6/dubtSF/EfKqQfbFX/MOASuZUWBu5BILmLQ748ItzjEeqVcNQPr7ooR/YRMraPPGMNt9vg1GbQT4BcoUgmlMT2oLvkTpm0DbG1s5ttgoFCAOwasiJUw2VgEOr0p66WTRVJWmJfS19m8Gp95th1v9hejizN/IkZ3872nKG/Qr3fqEA="
install: "pip install -r requirements.txt"
script: nosetests unittest.py
